name 'poise-s3'
maintainer 'Luis Felipe Moura Pereira De Siqueira'
maintainer_email 'LouTheBrew@gmail.com'
license 'MIT'
description 'provides s3 resources'
long_description 'provides s3 resources'
version '0.0.2'

depends 'poise'
depends 'poise-python'
