name 's3'
maintainer 'Luis Felipe Moura Pereira De Siqueira'
maintainer_email 'LouTheBrew@gmail.com'
license 'MIT'
description 'provides s3 resources'
long_description 'provides s3 resources'
version '1.0.0'

depends 'poise'
depends 'poise-python'
